spring.application.name=hostel-mess-waste
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mess_waste_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=pratik@77777
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MongoDB (used for feedback)
spring.data.mongodb.uri=mongodb://localhost:27017/mess_waste_feedback

# JWT (used in Module 2)
app.jwt.secret=hostel-mess-waste-super-secret-key-change-this-to-a-long-random-string-123456
app.jwt.expiration-ms=86400000

# Swagger UI: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html